POST https://vdc.company.com/api/admin/org/ORGID/vdcsparams
Accept: application/*+xml;version=31.0
Content-Type: application/vnd.vmware.admin.createVdcParams+xml
x-vcloud-authorization: THE_TOKEN

<?xml version="1.0" encoding="UTF-8"?>
<CreateVdcParams xmlns="http://www.vmware.com/vcloud/v1.5" name="The_name_of_the_vdc">
   <Description>MyDescription</Description>
   <AllocationModel>AllocationVApp</AllocationModel>
   <ComputeCapacity>
      <Cpu>
         <Units>MHz</Units>
         <Allocated>0</Allocated>
         <Limit>50000</Limit>
         <Reserved>0</Reserved>
         <Used>0</Used>
      </Cpu>
      <Memory>
         <Units>MB</Units>
         <Allocated>0</Allocated>
         <Limit>307200</Limit>
         <Reserved>0</Reserved>
         <Used>0</Used>
      </Memory>
   </ComputeCapacity>
   <NicQuota>0</NicQuota>
   <NetworkQuota>10</NetworkQuota>
   <VmQuota>10</VmQuota>
   <VdcStorageProfile>
      <Enabled>true</Enabled>
      <Units>MB</Units>
      <Limit>20480</Limit>
      <Default>true</Default>
       <ProviderVdcStorageProfile href="https://vdc.company.com/api/admin/pvdcStorageProfile/9a9a9a9a-aaaa-bbbb-cccc-dddddddddddd" id="urn:vcloud:providervdcstorageprofile:9a9a9a9a-aaaa-bbbb-cccc-dddddddddddd" name="STORAGE_NAME" type="application/vnd.vmware.admin.pvdcStorageProfile+xml"/>
   </VdcStorageProfile>
   <ResourceGuaranteedMemory>0.0</ResourceGuaranteedMemory>
   <ResourceGuaranteedCpu>0.0</ResourceGuaranteedCpu>
   <VCpuInMhz>1000</VCpuInMhz>
   <IsThinProvision>false</IsThinProvision>
   <ProviderVdcReference href="https://vdc.company.com/api/admin/providervdc/bcbc-aaaa-1111-2222-3333-44444444444" name="THE RESOURCE" type="application/vnd.vmware.admin.providervdc+xml"/>  
   <UsesFastProvisioning>false</UsesFastProvisioning>
</CreateVdcParams>
